name: CI Build & Push to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
          pytest -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
          platforms: linux/amd64

      - name: Write image tag
        run: echo "IMAGE_TAG=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}" >> $GITHUB_OUTPUT